### ISSUE TITLE
Version 1.4.1 won't install helper tool

### ISSUE THREAD

**Issue by etrahretep** [Oct4Pie/archify#11]
When batch processing it asks to install helper tool and ends with: log messages: Failed to install helper tool

**Comment by Oct4Pie** [comment]
Please retry with the latest version
It seems notarization had modified the app's identifier format

**Comment by etrahretep** [comment]
Takes me 1 step further. Full disk access is shown but not showing in preferences. Adding it manually doesn't work.
Removing with  tccutil reset All com.oct4pie.archify neither...
Suggestion?

**Comment by Oct4Pie** [comment]
Maybe you can try this debug version, which removes the old helper first
[archify.zip](https://github.com/user-attachments/files/17946945/archify.zip)

**Comment by etrahretep** [comment]
No change. After entering pw to install helper popup for FDA is shown which takes me to prefs where Archify is not shown. Again adding it manually doesn't help. Even tried turning SIP on. Running 15.2 bèta (24C5089c) on a Mac mini M4 Pro with SIP off. Even tried deleting TCC db for both system and user...

**Comment by Oct4Pie** [comment]
That is a bit strange
I am also on 15.2 Beta (24C5089c), and it works correctly
I am looking at potential causes

**Comment by Oct4Pie** [comment]
I bumped the helper tool bundle version to force reinstalling
[archify.zip](https://github.com/user-attachments/files/17947862/archify.zip)

**Comment by etrahretep** [comment]
Yeah that worked! THANKS!!
Other question. Is there a way to batch process the apps in my user folder without copying them all to the stems App folder? They're in an app folder named Applications and I tried hardlinking the folder to the stem App folder.

**Comment by Oct4Pie** [comment]
Yes, actually I am adding this option as I personally need it as well.
It will be in the next patch

**Comment by etrahretep** [comment]
Thanks, looking forward
