### ISSUE TITLE
feature request: dry-run default: preserve found binaries unless `--clean`

### ISSUE THREAD

**Issue by buckleyc** [Oct4Pie/archify#2]
Issue: this app seems to delete found files as the default without offering the user a choice.
Suggestion: My suggestion is to refactor the code to place `clean_dir()` action (and possibly any signing) inside a conditional, thus having a non-destructive default, and add the `--clean` option, to allow the user to `clean_dir()` and sign the found results.

**Comment by Oct4Pie** [comment]
Thanks for your input.
I assume you are referring to the python script.
May you clarify what exactly are you suggesting? You want to duplicate the app without cleaning binaries and signing?
Or you want to have control over which binaries are cleaned/signed?

**Comment by buckleyc** [comment]
If you are familiar with tools such as `git`, `rsync`, or `make`, you may have noticed they provide an option to simulate the intended action without making any changes but properly reporting what would be modified (e.g., deleted). These tools provide `-n` as the short option for dry-run.
I feel that tools which could execute a destructive act (e.g., deleting system files) should have a safety valve to prevent a user from doing something they could later regret.
Even the destructive `rm` command provides the `-i` option to help newbies from hurting themselves.

**Comment by Oct4Pie** [comment]
I see what you mean. You want to this feature exclusively for the python script?
This can be implemented but the reason that the script duplicates the app is exactly this. It lets the user try and test the outcome without changing the original application folder.

Therefore, running rsync on the duplicated, modified application should produce what you are looking for. How do you think this may be added as a feature in this case?
