### ISSUE TITLE
Git says the latest release says...

### ISSUE THREAD

**Issue by DataZombies** [Oct4Pie/archify#3]
...1.2.0. However, the app says 1.1.0.

<img width="396" alt="Screenshot 2024-07-16 at 4 33 11 PM" src="https://github.com/user-attachments/assets/6be4d56b-6a84-4f37-9b5c-2f0e97944a17">

**Comment by Oct4Pie** [comment]
Thanks for pointing it out
This has been addressed in 1.3.0
