### ISSUE TITLE
Archify asks for full disk permission, even if its added to Full Disk Access in macos

### ISSUE THREAD

**Issue by unbrokendub** [Oct4Pie/archify#4]
Trying to some apps in Batch Processor mode, but on the helper installation stage it asks for full disk access, every time, even if added already.

<img width="488" alt="image" src="https://github.com/user-attachments/assets/920389da-7838-43c2-a9fc-167517e39c38">

**Comment by Oct4Pie** [comment]
May you provide your macOS and archify version?

**Comment by unbrokendub** [comment]
Latest Archify(was downloaded today) 1.3 I think and macOS Sonoma 14.6. MacBook Air m2

**Comment by Oct4Pie** [comment]
I was not able to replicate the error in Sonoma 14.6.1, MacBook Air M2.
Have you tried removing `com.oct4pie` from the list, and going through the process again?
And to be sure, this is the message you are getting?
<img width="372" alt="01" src="https://github.com/user-attachments/assets/06292c35-1b5b-4c9d-a6db-a4f750cb1c7f">

**Comment by unbrokendub** [comment]
Yes. Exactly this message. I tried deleted Archify and com.oct4pie and tried to make it from the start. Not succesed. Maybe there is the way to manually install the helper?

**Comment by Oct4Pie** [comment]
[archify.app.zip](https://github.com/user-attachments/files/16605018/archify.app.zip)
Please try this patch and let me know if the issue is resolved

**Comment by unbrokendub** [comment]
Yes. Now it works! Thanks for fast response!

**Comment by Oct4Pie** [comment]
You are welcome. The app should be updated soon
