### ISSUE TITLE
Полный доступ к диску

### ISSUE THREAD

**Issue by AardSkelige** [Oct4Pie/archify#5]
После выдачи доступа к диску, приложение все равно требует полный доступ и не выполняет очистку.

**Comment by Oct4Pie** [comment]
Which version of the application are you using? Please provide the exact version number.
What version of macOS are you running? Include the version number (e.g., 13.6).
Can you provide any logs or screenshots?

**Comment by AardSkelige** [comment]
<img width="339" alt="Снимок экрана 2024-09-20 в 13 21 18" src="https://github.com/user-attachments/assets/10e5dd3d-a6e3-4365-9b35-40be916d49d4">
<img width="1062" alt="Снимок экрана 2024-09-20 в 13 21 51" src="https://github.com/user-attachments/assets/e35cb650-bbef-4bf2-a0dd-c280ed54abc5">

**Comment by AardSkelige** [comment]
<img width="563" alt="image" src="https://github.com/user-attachments/assets/db1b925c-472d-4069-88f8-703edca554b1">
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/c0becfcf-0b06-420d-8bcf-a3e586624eb3">

**Comment by Oct4Pie** [comment]
Please try enabling "com.oct4pie"
<img width="481" alt="Screenshot 2024-09-21 at 5 58 15 AM" src="https://github.com/user-attachments/assets/4f5d24de-c5e9-4659-ad89-f5dc08537dab">

**Comment by AardSkelige** [comment]
Спасибо. Все заработало.

**Comment by AardSkelige** [comment]
Спасибо. Все заработало.
