### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by AardSkelige** [Oct4Pie/archify#6]
Не запускается на другом маке. При запуске не просит доступ к диску вообще

https://github.com/user-attachments/assets/b36e9178-aa88-4ec2-84a0-6a515789c78c

![photo_2024-09-22 12 31 46](https://github.com/user-attachments/assets/41101cff-b4bf-415b-905e-b357a4818bd1)
![photo_2024-09-22 12 31 49](https://github.com/user-attachments/assets/271a5059-8b60-489b-8e98-bf8f4cdfc0cc)

**Comment by Oct4Pie** [comment]
Can you check the terminal.app output when you run the executable (archify)?

**Comment by AardSkelige** [comment]
Как это сделать?

**Comment by Oct4Pie** [comment]
Yes, and it will log the events and actions

**Comment by AardSkelige** [comment]
Я честно не понимаю что мне нажимать и что показать. Могли бы вы написать необходимую последовательность действий?
