### ISSUE TITLE
Full disk Access bug

### ISSUE THREAD

**Issue by IvanoPashi** [Oct4Pie/archify#7]
I get a "full disk access" bug on my MacBook pro 15 late 2013 with Big Sur. Sorry for non-English screenshots. 

I restarted the app and the system several times but got the same error every time. 

The App version is v1.3.1

<img width="1440" alt="1" src="https://github.com/user-attachments/assets/73dd6a60-c35c-4f71-b6a1-12a339f0972f">
<img width="1440" alt="2" src="https://github.com/user-attachments/assets/98a5984c-8af0-455a-b83a-b333fb601337">
<img width="1440" alt="3" src="https://github.com/user-attachments/assets/ec3d6768-24ef-47c6-acfb-c87da8fe7a88">

**Comment by Oct4Pie** [comment]
Please refer to #6
Just mark "com.oct4pie"

<img width="827" alt="Screenshot 2024-09-22 at 4 55 41 PM" src="https://github.com/user-attachments/assets/3647a8a9-dfc2-406a-ac96-b452c05a86b8">

**Comment by IvanoPashi** [comment]
Sorry, but I don't have it. Even in the list for permissions.

**Comment by Oct4Pie** [comment]
Please check if `/Library/PrivilegedHelperTools/com.oct4pie.archifyhelper` can be added via the + button
If it does not exist, let me know

**Comment by IvanoPashi** [comment]
I deleted the latest release and installed [v1.2.0-fix](https://github.com/Oct4Pie/archify/releases/tag/v1.2.0-fix). Everything works now. The settings found com.oct4pie helper and I gave permission to it. 

<img width="1440" alt="Снимок экрана 2024-09-24 в 13 27 21" src="https://github.com/user-attachments/assets/49311fce-9279-428a-bc8c-0bfc32129e49">

**Comment by Oct4Pie** [comment]
I understand. It seems the latest Xcode is causing issues with privilege escalation.
I will address this and let you know

**Comment by alessdangelo** [comment]
Just had the same issue, I followed everything you said in this and the others issues, I couldn't go past the "Full Disk Access required" with software up to date. But had no issue using the 1.2.0-fix

**Comment by Genxster1998** [comment]
Full Disk Access bug persist on MacOS 15.5 , Intel , I manually added Archify like 100 of times from System Settings , it still install helper tool and says to enable full disk access from System Settings everytime i batch process.
